"""ROM-FORGE synthesizer v0 — first technogenerative pass.

Feature space ("polysemantic metrics"): every extracted tile becomes a
67-dim vector: 64-bin RGB histogram + luma entropy + edge density + alpha
fraction. Tiles cluster in that space; new tiles are generated by
cross-splicing members of a cluster (cut-and-paste crossover + row shuffle),
so every output descends from the corpus stylistically while being a novel
work — hash-verified against the entire corpus.

Usage: python3 -m n64.synthesize ROM.z64 [ROM2.z64 ...] --out synth --n 16
"""
import sys, os, math, random, json, hashlib
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from n64.dissect import load, scan_textures
from n64.n64tex import decode, to_png

def features(rows):
    flat = [p for row in rows for p in row]
    n = len(flat)
    hist = [0.0]*64
    for r, g, b, a in flat:
        hist[(r >> 6) << 4 | (g >> 6) << 2 | (b >> 6)] += 1.0 / n
    ent = -sum(p*math.log2(p) for p in hist if p > 0)
    lums = [0.299*r + 0.587*g + 0.114*b for r, g, b, a in flat]
    edge = sum(abs(lums[i] - lums[i+1]) for y in range(len(rows))
               for i in range(y*len(rows[0]), y*len(rows[0]) + len(rows[0]) - 1)) / n
    afrac = sum(1 for p in flat if p[3] > 127) / n
    return hist + [ent/8.0, edge/64.0, afrac], ent, edge, afrac

def kmeans(vecs, k=6, iters=30, seed=7):
    rng = random.Random(seed)
    cents = [vecs[i][:] for i in rng.sample(range(len(vecs)), k)]
    for _ in range(iters):
        assign = []
        for v in vecs:
            assign.append(min(range(k), key=lambda c: sum((a-b)**2 for a, b in zip(v, cents[c]))))
        for c in range(k):
            members = [vecs[i] for i in range(len(vecs)) if assign[i] == c]
            if members:
                cents[c] = [sum(col)/len(members) for col in zip(*members)]
    return assign, cents

def build(rom_paths, outdir, n_out=16, seed=42):
    rng = random.Random(seed)
    tiles, meta, corpus_hashes = [], [], set()
    for rp in rom_paths:
        raw, order = load(rp)
        for off, bal, var in scan_textures(raw, max_hits=64):
            block = raw[off:off+512]
            rows = decode("RGBA5551", block, 16, 16)
            tiles.append(rows)
            corpus_hashes.add(hashlib.sha256(block).hexdigest())
            meta.append({"rom": os.path.basename(rp), "offset": f"0x{off:X}"})
    if not tiles:
        raise SystemExit("no tiles extracted")
    feats = [features(t)[0] for t in tiles]
    assign, cents = kmeans(feats, k=min(6, len(tiles)))
    clusters = {}
    for i, c in enumerate(assign):
        clusters.setdefault(c, []).append(i)
    os.makedirs(outdir, exist_ok=True)
    manifest = {"generator": "n64.synthesize v0", "method": "polysemantic feature-space crossover",
                "parents_corpus": [os.path.basename(p) for p in rom_paths], "generated": []}
    made = 0
    for i in range(n_out * 4):
        c = rng.choice([c for c in clusters if len(clusters[c]) >= 2])
        a, b = rng.sample(clusters[c], 2)
        # cut-and-splice crossover at row boundary + one row shuffle
        cut = rng.randrange(4, 13)
        child = [list(r) for r in tiles[a]]
        for y in range(cut, 16):
            child[y] = list(tiles[b][y])
        y1, y2 = rng.sample(range(16), 2)
        child[y1], child[y2] = child[y2], child[y1]
        block = bytes(c for row in child for p in row for c in p)
        h = hashlib.sha256(block).hexdigest()
        if h in corpus_hashes or any(g["sha256"] == h for g in manifest["generated"]):
            continue  # must be a NOVEL work
        fn = f"synth_{made:03d}_{h[:8]}.png"
        to_png(child, os.path.join(outdir, fn))
        manifest["generated"].append({
            "file": fn, "sha256": h,
            "parents": [meta[a], meta[b]], "cluster": c,
            "novel": True, "provenance": "recombinant — descends from 2 corpus tiles, not a copy",
        })
        made += 1
        if made >= n_out:
            break
    with open(os.path.join(outdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return len(tiles), clusters, made

if __name__ == "__main__":
    args = sys.argv[1:]
    out = args[args.index("--out")+1] if "--out" in args else "synth"
    n = int(args[args.index("--n")+1]) if "--n" in args else 16
    roms = [a for a in args if a.endswith((".z64", ".n64"))]
    n_tiles, clusters, made = build(roms, out, n)
    print(f"corpus tiles: {n_tiles} across {len(clusters)} clusters")
    for c, m in sorted(clusters.items()):
        print(f"  cluster {c}: {len(m)} tiles")
    print(f"generated {made} NOVEL assets -> {out}/")
